# Ansible managed

apiVersion: v2
name: beacon-metrics-gazer
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
dependencies:
  - name: beacon-metrics-gazer
    repository: https://ethpandaops.github.io/ethereum-helm-charts
    version: 0.1.3
