# Ansible managed

apiVersion: v2
name: forkmon
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
dependencies:
  - name: forkmon
    repository: https://ethpandaops.github.io/ethereum-helm-charts
    version: 0.1.4
