# Ansible managed

apiVersion: v2
name: blobscan
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
dependencies:
  - name: blobscan
    repository: https://blobscan.github.io/blobscan-helm-charts/
    version: 0.2.6
  - name: blobscan-api
    repository: https://blobscan.github.io/blobscan-helm-charts/
    version: 0.2.5
  - name: blobscan-indexer
    repository: https://blobscan.github.io/blobscan-helm-charts/
    version: 0.2.7
