# Ansible managed

apiVersion: v2
name: faucet-2
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
dependencies:
  - name: eth-faucet
    repository: https://ethpandaops.github.io/ethereum-helm-charts
    version: 0.1.1
