# Ansible managed

apiVersion: v2
name: blockscout
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
dependencies:
  - name: blockscout
    repository: https://ethpandaops.github.io/ethereum-helm-charts
    version: 0.2.0
