# Ansible managed

checkpointz:
  fullnameOverride: checkpointz
  replicas: 1

  image:
    repository: ethpandaops/checkpointz
    tag: 0.15.0

  resources:
    requests:
      cpu: 64m
      memory: 256Mi
  ingress:
    enabled: true
    className: ingress-nginx-public
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-production
    hosts:
      - host: checkpoint-sync.whisk-testnet-0.ethpandaops.io
        paths:
          - path: /
            pathType: Prefix

    tls:
    - hosts:
      - checkpoint-sync.whisk-testnet-0.ethpandaops.io
      secretName: whisk-testnet-0-checkpoint-sync-tls

  config:
    global:
      listenAddr: ":5555"
      logging: "info" # panic,fatal,warm,info,debug,trace
      metricsAddr: ":9090"

    checkpointz:
      mode: full
      caches:
        blocks:
          max_items: 100
        states:
          max_items: 5
      historical_epoch_count: 20

    beacon:
      upstreams:
      - name: rpc-lodestar-nethermind-001
        address: http://lodestar-nethermind-001:5052
        dataProvider: true
      - name: bootnode-1
        address: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.4844-devnets.node_ingress.combined}>@bn.bootnode-1.srv.whisk-testnet-0.ethpandaops.io
        dataProvider: true
      - name: lighthouse-geth-1
        address: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.4844-devnets.node_ingress.combined}>@bn.lighthouse-geth-1.srv.whisk-testnet-0.ethpandaops.io
        dataProvider: true
      - name: lighthouse-geth-10
        address: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.4844-devnets.node_ingress.combined}>@bn.lighthouse-geth-10.srv.whisk-testnet-0.ethpandaops.io
        dataProvider: true
      - name: lighthouse-geth-2
        address: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.4844-devnets.node_ingress.combined}>@bn.lighthouse-geth-2.srv.whisk-testnet-0.ethpandaops.io
        dataProvider: true
      - name: lighthouse-geth-3
        address: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.4844-devnets.node_ingress.combined}>@bn.lighthouse-geth-3.srv.whisk-testnet-0.ethpandaops.io
        dataProvider: true
      - name: lighthouse-geth-4
        address: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.4844-devnets.node_ingress.combined}>@bn.lighthouse-geth-4.srv.whisk-testnet-0.ethpandaops.io
        dataProvider: true
      - name: lighthouse-geth-5
        address: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.4844-devnets.node_ingress.combined}>@bn.lighthouse-geth-5.srv.whisk-testnet-0.ethpandaops.io
        dataProvider: true
      - name: lighthouse-geth-6
        address: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.4844-devnets.node_ingress.combined}>@bn.lighthouse-geth-6.srv.whisk-testnet-0.ethpandaops.io
        dataProvider: true
      - name: lighthouse-geth-7
        address: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.4844-devnets.node_ingress.combined}>@bn.lighthouse-geth-7.srv.whisk-testnet-0.ethpandaops.io
        dataProvider: true
      - name: lighthouse-geth-8
        address: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.4844-devnets.node_ingress.combined}>@bn.lighthouse-geth-8.srv.whisk-testnet-0.ethpandaops.io
        dataProvider: true
      - name: lighthouse-geth-9
        address: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.4844-devnets.node_ingress.combined}>@bn.lighthouse-geth-9.srv.whisk-testnet-0.ethpandaops.io
        dataProvider: true
