name: Helm lint
on:
  pull_request:
    paths:
      - 'kubernetes/**'
      - '.tool-versions'
      - '.github/actions/**'
      - '.github/workflows/lint-helm.yaml'
  push:
    branches:
      - master
    paths:
      - 'kubernetes/**'
      - '.tool-versions'
      - '.github/actions/**'
      - '.github/workflows/lint-helm.yaml'

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - uses: ./.github/actions/setup
      - name: Lint
        run: >
          helm lint kubernetes/*/*
